### ISSUE TITLE
Grafana Navigation Included when not installed

### ISSUE THREAD

**Issue by whitej6** [nautobot/nautobot-plugin-chatops#241]
### Environment
* Python version:  NA
* Nautobot version: NA
* nautobot-plugin-chatops version:  2.0.2

### Steps to Reproduce
1.  Install chatops without grafana extras
2. click plugins navigation menu
3.

### Expected Behavior
Grafana links are omitted when not installed

### Observed Behavior
Grafana links return a link error
![image](https://github.com/nautobot/nautobot-plugin-chatops/assets/26559188/f6abb087-de72-463b-89f1-f9241eff6531)

**Comment by EdificomSA** [comment]
```
Grafana ChatOps integration is not available.
nautobot-docker-compose-nautobot-1   | Traceback (most recent call last):
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/urls.py", line 22, in <module>
nautobot-docker-compose-nautobot-1   |     from nautobot_chatops.integrations.grafana.urls import urlpatterns as grafana_urlpatterns
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/integrations/grafana/urls.py", line 5, in <module>
nautobot-docker-compose-nautobot-1   |     from nautobot_chatops.integrations.grafana.views import (
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/integrations/grafana/views.py", line 19, in <module>
nautobot-docker-compose-nautobot-1   |     from nautobot_chatops.integrations.grafana.diffsync.sync import run_dashboard_sync, run_panels_sync, run_variables_sync
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/integrations/grafana/diffsync/sync.py", line 4, in <module>
nautobot-docker-compose-nautobot-1   |     from nautobot_chatops.integrations.grafana.grafana import handler
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/integrations/grafana/grafana.py", line 378, in <module>
nautobot-docker-compose-nautobot-1   |     handler = GrafanaHandler(PLUGIN_SETTINGS)
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/integrations/grafana/grafana.py", line 60, in __init__
nautobot-docker-compose-nautobot-1   |     self.config = _get_settings_from_chatops(config)
nautobot-docker-compose-nautobot-1   |   File "/opt/nautobot/.local/lib/python3.10/site-packages/nautobot_chatops/integrations/grafana/grafana.py", line 38, in _get_settings_from_chatops
nautobot-docker-compose-nautobot-1   |     return GrafanaConfigSettings(
nautobot-docker-compose-nautobot-1   |   File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
nautobot-docker-compose-nautobot-1   | pydantic.error_wrappers.ValidationError: 1 validation error for GrafanaConfigSettings
nautobot-docker-compose-nautobot-1   | default_timespan
nautobot-docker-compose-nautobot-1   |   invalid duration format (type=value_error.duration)
```

**Comment by tylersiemers** [comment]
Confirm same issue. Setting 'enable_grafana': False doesn't work either and the links remain.

**Comment by smk4664** [comment]
Thanks! I will look into this. It should be behaving like the other integrations.
